# Scala Steward configuration
# https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md
pullRequests.frequency = "@weekly"
scalafmt.runAfterUpgrading = true
pullRequests.grouping = [
  { name = "circe", "title" = "Circe updates", "filter" = [{ "group" = "io.circe" }] },
  { name = "rdf4j", "title" = "RDF4J updates", "filter" = [{ "group" = "org.eclipse.rdf4j" }] },
  { name = "patches", "title" = "Patch updates", "filter" = [{ "version" = "patch" }] }
]
